# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: swift
# cache: cocoapods
# podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- pod repo update
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace Example/WistiaKit.xcworkspace -scheme WistiaKit-Example -sdk iphonesimulator12.0 -destination 'name=iPhone X' ONLY_ACTIVE_ARCH=YES | xcpretty
- pod lib lint
